apiVersion: dragonflydb.io/v1alpha1
kind: Dragonfly
metadata:
  name: dragonfly
  labels:
    app: dragonfly
    environment: production
spec:
  replicas: 2
  image: docker.dragonflydb.io/dragonflydb/dragonfly:v1.23.1
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 500m
      memory: 512Mi
