apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: course-app-repo
  namespace: flux-system
spec:
  interval: 1m
  url: https://github.com/timchukd/rd-fluxcd
  ref:
    branch: main
